permalink: /:year/:month/:day/:title.html
paginate: 10
#markdown: redcarpet

# 作者信息
author: 
  name: kidloserme
  email: whl1208@126.com
  link: http://kidloserme.github.io
  github: http://github.com/kidloserme

# 站点信息
title: 加贝龙的博客
description: BlogOfKidloserme
url: http://kidloserme.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/lone.jpg
favicon: /public/img/lone.jpg

# google analytics 设置
ga:
  id: UA-71787810-1
  url: kidloserme.github.io

# disqus 设置
#disqus:
 # shortname: painterlin

# 主题设置，自动激活某个标签
active: 学习

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
